# Generated by Django 2.2.20 on 2021-11-09 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('review_title', models.CharField(max_length=128)),
                ('review_content', models.CharField(max_length=3000)),
                ('review_url', models.CharField(max_length=255)),
                ('found_helpful', models.IntegerField(default=0)),
                ('verified_purchase', models.BooleanField(default=False)),
                ('product_name', models.CharField(max_length=255)),
            ],
        ),
    ]
