# Generated by Django 2.2.20 on 2021-11-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='username',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='product_name',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review_url',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='verified_purchase',
            new_name='verified',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
